image: docker:latest

stages:
  - build

variables:
  test: "CoffeeMachine.IntegrationTest"
  
before_script:
  - docker info
  - docker-compose --version

build:
  stage: build
  script:
    - docker-compose down
    - docker-compose build
    - docker-compose up --abort-on-container-exit
  artifacts: 
    paths:
      - /built-output