image: mcr.microsoft.com/dotnet/aspnet:8.0

stages:
  - build
  - test

variables:
  test: "CoffeeMachine.IntegrationTest"

before_script:
  - "ls"

build:
  stage: build
  script:
    - "docker compose up"
  artifacts: 
    paths:
      - /built-output