variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  
image: docker/compose:latest

stages:
  - build
  
before_script:
  - docker-compose --version

build:
  stage: build
  script:
    - docker-compose down
    - docker-compose build
    - docker-compose up --abort-on-container-exit
  artifacts: 
    paths:
      - /built-output