stages:
  - deploy
  - build
  - test

build_job:
  stage: build
  image: registry.tomskasu.ru/devops/dockerify/dotnetsdk:8.0
  script:
    - 'cd src/CoffeeMachine.API'
    - 'dotnet build'

test_job:
  stage: test
  image: registry.tomskasu.ru/devops/dockerify/dotnetsdk:8.0
  script:
    - 'cd src/CoffeeMachine.IntegrationTests'
    - 'dotnet test'
    - 'cd ../CoffeeMachine.UnitTests'
    - 'dotnet test'

deploy_job:
  stage: deploy
  image: docker:27
  services:
    - docker:27-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    - 'echo $CI_REGISTRY_PASSWORD | docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY'
    - 'cd deploy'
    - 'docker-compose up $CI_REGISTRY_IMAGE .'
    - 'docker-compose ps'
    - 'docker-compose down $CI_REGISTRY_IMAGE'