stages:
  - build
  - test

variables:
  test: "CoffeeMachine.IntegrationTest"

build:
  stage: build
  script:
    - docker compose docker-compose down
    - docker compose docker-compose build
    - docker compose docker-compose up --abort-on-container-exit
  artifacts: 
    paths:
      - /built-output