image: mcr.microsoft.com/dotnet/sdk:8.0

variables:
  OBJECTS_DIRECTORY: 'obj'
  NUGET_PACKAGES_DIRECTORY: '.nuget'
  SOURCE_CODE_PATH: 'src/CoffeeMachine.API'


stages:
  - build
  
before_script:
  - ls

build:
  stage: build
  script:
    - 'cd src'
    - 'dotnet restore --packages $NUGET_PACKAGES_DIRECTORY'
    - 'dotnet restore'
    - 'dotnet build'