image: docker:latest

services:
  - docker:dind
    
stages:
  - build
  
variables:
  DOCKER_HOST: tcp://192.168.65.0:24/
  DOCKER_DRIVER: overlay2
  
before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  script:
    - docker-compose build
    - docker-compose up --abort-on-container-exit