image: mcr.microsoft.com/dotnet/sdk:5.0

stages:
  - build
  - test

variables:
  ASPNETCORE_ENVIRONMENT: "Test"

before_script:
  - apt-get update -qq
  - apt-get install -y curl
  - curl -sL https://deb.nodesource.com/setup_14.x | bash -
  - apt-get install -y nodejs

build:
  stage: build
  script:
    - dotnet restore
    - dotnet build

test:
  stage: test
  script:
    - dotnet test