image: mcr.microsoft.com/dotnet/aspnet:5.0

stages:
  - build
  - test

variables:
  test: "CoffeeMachine.IntegrationTest"

before_script:
  - "cd src"
  - "dotnet --version"
  - "dotnet restore"

build:
  stage: build
  script:
    - "cd CoffeeMachine.API"
    - "dotnet build"

test:
  stage: test
  script:
    - "cd $CoffeeMachine.IntegrationTest"
    - "dotnet test"