image: docker:latest

services:
  - docker:dind
  
variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

stages:
  - build
  
build:
  stage: build
  script:
    - docker-compose build
    - docker-compose up