image: registry.tomskasu.ru/devops/dockerify/aspnet:8.0

variables:
  OBJECTS_DIRECTORY: 'obj'
  NUGET_PACKAGES_DIRECTORY: '.nuget'
  SOURCE_CODE_PATH: 'src/CoffeeMachine.API'


stages:
  - build
  - test
  
before_script:
  - ls

build:
  stage: build
  image: registry.tomskasu.ru/devops/dockerify/dotnetsdk:8.0
  script:
    - 'cd src/CoffeeMachine.API'
    - 'dotnet restore --packages $NUGET_PACKAGES_DIRECTORY'
    - 'dotnet restore'
    - 'dotnet build'

test:
  stage: test
  script:
    - 'cd ../src/CoffeeMachine.UnitTests'
    - 'dotnet test'