stages:
  - build
  - test

variables:
  test: "CoffeeMachine.IntegrationTest"

build:
  stage: build
  script:
    - docker compose docker-compose.yml down
    - docker compose docker-compose.yml build
    - docker compose docker-compose.yml up --abort-on-container-exit
  artifacts: 
    paths:
      - /built-output