version: '3.5'
networks:
  coffeemachine_net:
    driver: bridge

services:
  coffeemachine.api:
    image: coffeemachine.api
    container_name: coffeemachine.api
    build:
      context: .
      dockerfile: src/CoffeeMachine.API/Dockerfile
    ports:
      - 5000:5000
    networks:
      - coffeemachine_net
    depends_on:
      - coffeemachine_db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionString=host=postgres-container;port=5432;database=CoffeeMachine;Username=postgres;Password=toor;

  coffeemachine_db:
    container_name: postgres-container
    image: postgres:16.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: toor
      POSTGRES_DB: CoffeeMachine
    ports:
      - "5432:5432"
    networks:
      coffeemachine_net:
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: