// <auto-generated />
using System;
using CoffeeMachine.Persistence.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoffeeMachine.Persistence.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240412062617_InitialRemake")]
    partial class InitialRemake
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BanknoteMachine", b =>
                {
                    b.Property<long>("BanknotesId")
                        .HasColumnType("bigint");

                    b.Property<long>("MachinesId")
                        .HasColumnType("bigint");

                    b.HasKey("BanknotesId", "MachinesId");

                    b.HasIndex("MachinesId");

                    b.ToTable("BanknoteMachine");
                });

            modelBuilder.Entity("CoffeeMachine.Domain.Models.Banknote", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<int>("Par")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("money_pk");

                    b.ToTable("Banknotes");
                });

            modelBuilder.Entity("CoffeeMachine.Domain.Models.Coffee", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("coffee_pk");

                    b.ToTable("Coffees");
                });

            modelBuilder.Entity("CoffeeMachine.Domain.Models.Machine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<int?>("Balance")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id")
                        .HasName("machine_pk");

                    b.ToTable("Machines");
                });

            modelBuilder.Entity("CoffeeMachine.Domain.Models.Purchase", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<long>("CoffeeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("MachineId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id")
                        .HasName("purchase_pk");

                    b.HasIndex("CoffeeId");

                    b.HasIndex("MachineId");

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("CoffeeMachine.Domain.Models.Transaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<long>("BanknoteId")
                        .HasColumnType("bigint");

                    b.Property<int>("CountBanknotes")
                        .HasColumnType("integer");

                    b.Property<long>("PurchaseId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Type")
                        .HasColumnType("boolean");

                    b.HasKey("Id")
                        .HasName("transaction_pk");

                    b.HasIndex("BanknoteId");

                    b.HasIndex("PurchaseId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("BanknoteMachine", b =>
                {
                    b.HasOne("CoffeeMachine.Domain.Models.Banknote", null)
                        .WithMany()
                        .HasForeignKey("BanknotesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoffeeMachine.Domain.Models.Machine", null)
                        .WithMany()
                        .HasForeignKey("MachinesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CoffeeMachine.Domain.Models.Purchase", b =>
                {
                    b.HasOne("CoffeeMachine.Domain.Models.Coffee", "Coffee")
                        .WithMany("Purchases")
                        .HasForeignKey("CoffeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("purchase_coffee_fk");

                    b.HasOne("CoffeeMachine.Domain.Models.Machine", "Machine")
                        .WithMany("Purchases")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("purchase_machine_fk");

                    b.Navigation("Coffee");

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("CoffeeMachine.Domain.Models.Transaction", b =>
                {
                    b.HasOne("CoffeeMachine.Domain.Models.Banknote", "Banknote")
                        .WithMany("Transactions")
                        .HasForeignKey("BanknoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("transaction_banknote_fk");

                    b.HasOne("CoffeeMachine.Domain.Models.Purchase", "Purchase")
                        .WithMany("Transactions")
                        .HasForeignKey("PurchaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("transaction_purchase_fk");

                    b.Navigation("Banknote");

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("CoffeeMachine.Domain.Models.Banknote", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("CoffeeMachine.Domain.Models.Coffee", b =>
                {
                    b.Navigation("Purchases");
                });

            modelBuilder.Entity("CoffeeMachine.Domain.Models.Machine", b =>
                {
                    b.Navigation("Purchases");
                });

            modelBuilder.Entity("CoffeeMachine.Domain.Models.Purchase", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
